### ISSUE TITLE
Unloading day: Attach scoring system to sorting area

### ISSUE THREAD

**Issue by myhairisblue** [DantesGearbox/Prototype5#10]
During the first day, the player only has to put down the crates on the sorting area (represented by the green "rug") for the crates to disappear and earn them points. 

- [x] Make crates disappear when they are put down on top of the sorting area
- [x] Add 100 points to score for each crate

**Comment by DantesGearbox** [comment]
I just put a horizontal WinQuad on top of the rug. It destroys any crates that come in contact and it adds a 100 points for each correct crate. NOTE: It also subtracts 50 points if you move a wrong crate on top of it. So don't spawn the wrong crates.
