### ISSUE TITLE
Unloading day: Handle truck departures

### ISSUE THREAD

**Issue by myhairisblue** [DantesGearbox/Prototype5#13]
Trucks leave at set times, stored in the GameManager object. When these times are reached, the following must be done: 

- [x] Teleport player out of the truck and into the warehouse if they are inside it
- [x] Move / destroy container/truck
- [x] Move / destroy crates still in truck
- [x] Subtract 50 points from score for each crate destroyed
- [x] Place barrier at bay door to prevent player from walking out of the warehouse

**Comment by Jalict** [comment]
Seems like GameManager could easily contain a lot of things. I would decouple it into its own Manager, *TruckManager*!
