### ISSUE TITLE
Sorting day: Create GameManager

### ISSUE THREAD

**Issue by myhairisblue** [DantesGearbox/Prototype5#14]
The GameManager object in the sorting day works slightly differently to the one in the unloading day. 

- [x] Keep track of score
- [x] Keep track of round timing (3 minutes)
- [x] Spawn crates on the unloading area throughout the entire round
- [ ] End round, post score and return to main menuwhen time runs out

**Comment by Jalict** [comment]
Maybe we should also handle the Day/Scene management in here? Such as switching to new level.

**Comment by Jalict** [comment]
Also the unloading part. I think we should seperate this into its own Script. Mostly due to this being unique for one Scene.
