### ISSUE TITLE
Sorting day: Create goal quads

### ISSUE THREAD

**Issue by myhairisblue** [DantesGearbox/Prototype5#15]
The goal quads are placed on the conveyor belts, past the point where the player is able to go. They act as triggers; when a crate touches one of them, the crate is destroyed. If the crate is of the correct type, 100 points are added to the score; otherwise, 50 points are subtracted from the score. 

- [x] Crate destroying functionality
- [x] Points functionality

**Comment by Jalict** [comment]
I imagine a trigger box with a make a quad on one side (Or could just be a cube with a sprite on each side of the cube) which is located on the conveyor belt.

**Comment by DantesGearbox** [comment]
It is now functional. Prefab is in prefabs folder, example implementation in scene "main".
