### ISSUE TITLE
Game Score shows after second game

### ISSUE THREAD

**Issue by Jalict** [DantesGearbox/Prototype5#27]
How to reproduce bug:
1. Play full round of a day (doesn't matter which)
2. Go to main menu when day is finished
3. Enter a new day (doesn't matter which, as long as it isn't the same)
4. The screen should now show you the score for the previous day and you can't play. You have to restart the game to fix the issue.

**Comment by myhairisblue** [comment]
I think this has a lot to do with GameManager not being destroyed on load. The variables should either be reset when the scene is loaded, or we just rebuild the GameManager on load every time

**Comment by Jalict** [comment]
I think it would be the best that the singleton doesn't get destroyed (The generel purpose of the singleton) but yes it has something to do with that I presume.
Resetting stuff might do it. I think we have to look at the condition for showing the score and when it gets disabled/enabled.

**Comment by myhairisblue** [comment]
Should be fixed now.
